on:
  push:
    tags:
      - '[0-9].[0-9].[0-9]'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup gradlew
        run: chmod +x ./gradlew

      - name: compile client
        run: ./gradlew -q dekstop:dist

      - name: compile server
        run: ./gradlew -q server:dist

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: true
          prerelease: false

      - name: Upload Release Client
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./desktop/build/libs/RealmTech-${{ github.ref_name }}.jar
          asset_name: RealmTech-${{ github.ref_name }}.jar
          asset_content_type: application/java-archive

      - name: Upload Release Server
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./server/build/libs/RealmTech-${{ github.ref_name }}.jar
          asset_name: RealmTech-${{ github.ref_name }}.jar
          asset_content_type: application/java-archive